// Auto-generated by levelc.py
#include <stdint.h>
#include "levels/boot_audit-blob.h"

const uint8_t boot_audit_blob[] = {
#embed "../../assets/levels/boot_audit.bin"
};
const uint32_t boot_audit_blob_size = (uint32_t)sizeof(boot_audit_blob);
