// Auto-generated by levelc.py
#pragma once

typedef enum FlagId : unsigned char {
  LOCKER_L3_OPEN = 0,
  GOT_BADGE = 1,
  GOT_FUSE = 2,
  GOT_SCREWDRIVER = 3,
  GOT_LOG_TAPE_01 = 4,
  RELAYS_OK = 5,
  FUSE_INSTALLED = 6,
  BADGE_SWIPED = 7,
  STATUS_GREEN = 8,
  FlagId__COUNT = 9
} FlagId;

typedef enum VarId : unsigned char {
  RELAY_BITS = 0,
  VarId__COUNT = 1
} VarId;

typedef enum ItemId : unsigned char {
  BADGE_MAINT3 = 0,
  FUSE_BLUE = 1,
  SCREWDRIVER = 2,
  LOG_TAPE_01 = 3,
  CREDITS = 4,
  ItemId__COUNT = 5
} ItemId;

typedef enum MsgId : unsigned char {
  WAKE_EVENT = 0,
  ORACLE_WELCOME = 1,
  MANIFEST_PIN = 2,
  LOCKER_OPENED = 3,
  LOCKER_BAD_CODE = 4,
  MIRA_HINT = 5,
  RELAY_SIGN = 6,
  PANEL_NO_POWER = 7,
  PANEL_POWER_OK = 8,
  RELAYS_WRONG = 9,
  RELAYS_RIGHT = 10,
  FUSE_SEATED = 11,
  BADGE_OK = 12,
  MAGLOCK_RELEASED = 13,
  LOG_TAPE_FOUND = 14,
  LOG_TAPE_TEXT = 15,
  ZAP = 16,
  MsgId__COUNT = 17
} MsgId;

typedef enum ObjType : unsigned char {
  OBJ_SIGN = 1,
  OBJ_PICKUP = 2,
  OBJ_LOCKER_KEYPAD = 3,
  OBJ_BREAKER_PANEL = 4,
  OBJ_HATCH_PANEL = 5,
  OBJ_EXIT_TRIGGER = 6,
  OBJ_NPC_INTERCOM = 7,
} ObjType;

